---
title: "FACET RQ3"
author: "blinded for review"
date: "`r Sys.Date()`"
output:
  word_document: default
  pdf_document:
    number_sections: true
    latex_engine: xelatex
subtitle: Model summaries
geometry: margin=0.7in
urlcolor: blue
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(brms)

outcomes <- c("mean_fixation_duration", "mean_fixation_number",
	      "latencies", "rel_gaze_in_aoi")
quality_measures <- c("acc_visd", "precrms_visd", "precsd_visd", "robustness_prop_2")

comparisons <- list()
for(outcome in outcomes) {
	red_model <- read_rds(paste("red_rq3_", outcome, ".rds", sep=""))
	loo_red <- loo(red_model)
	for(measure in quality_measures) {
		name <- paste(outcome, measure, sep="_")
		full_model <- read_rds(paste("full_rq3_", name, ".rds", sep=""))
		loo_full <- loo(full_model)
		comparisons[[name]] <- loo_compare(loo_full, loo_red)
	}
}
```

# Mean fixation duration

## Accuracy

```{r}
kable(comparisons[["mean_fixation_duration_acc_visd"]])
```

## Precision (RMS)

```{r}
kable(comparisons[["mean_fixation_duration_precrms_visd"]])
```

## Precision (SD)

```{r}
kable(comparisons[["mean_fixation_duration_precsd_visd"]])
```

## Robustness

```{r}
kable(comparisons[["mean_fixation_duration_robustness_prop_2"]])
```

# Mean fixation number

## Accuracy

```{r}
kable(comparisons[["mean_fixation_number_acc_visd"]])
```

## Precision (RMS)

```{r}
kable(comparisons[["mean_fixation_number_precrms_visd"]])
```

## Precision (SD)

```{r}
kable(comparisons[["mean_fixation_number_precsd_visd"]])
```

## Robustness

```{r}
kable(comparisons[["mean_fixation_number_robustness_prop_2"]])
```

# Latencies

## Accuracy

```{r}
kable(comparisons[["latencies_acc_visd"]])
```

## Precision (RMS)

```{r}
kable(comparisons[["rel_gaze_in_aoi_precrms_visd"]])
```

## Precision (SD)

```{r}
kable(comparisons[["rel_gaze_in_aoi_precsd_visd"]])
```

## Robustness

```{r}
kable(comparisons[["rel_gaze_in_aoi_robustness_prop_2"]])
```

# Relative gaze in AOI

## Accuracy

```{r}
kable(comparisons[["rel_gaze_in_aoi_acc_visd"]])
```

## Precision (RMS)

```{r}
kable(comparisons[["rel_gaze_in_aoi_precrms_visd"]])
```

## Precision (SD)

```{r}
kable(comparisons[["rel_gaze_in_aoi_precsd_visd"]])
```

## Robustness

```{r}
kable(comparisons[["rel_gaze_in_aoi_robustness_prop_2"]])
```
